# Copyright 2025 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# MoveIt uses this configuration for controller management

<<<<<<< HEAD
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
=======
moveit_controller_manager: moveit_ros_control_interface/MoveItControllerManager

# Trajectory execution parameters
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true

moveit_ros_control_interface:
>>>>>>> 2569ad2 (feat: control)
  controller_names:
    - left_joint_trajectory_controller
    - right_joint_trajectory_controller
    - left_gripper_controller
    - right_gripper_controller

  left_joint_trajectory_controller:
<<<<<<< HEAD
    type: FollowJointTrajectory
=======
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
>>>>>>> 2569ad2 (feat: control)
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
<<<<<<< HEAD
    action_ns: follow_joint_trajectory
    default: true
  right_joint_trajectory_controller:
    type: FollowJointTrajectory
=======
  
  right_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
>>>>>>> 2569ad2 (feat: control)
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
<<<<<<< HEAD
    action_ns: follow_joint_trajectory
    default: true
  left_gripper_controller:
    type: GripperCommand
    joints:
      - openarm_left_finger_joint1
    action_ns: gripper_cmd
    default: true
  right_gripper_controller:
    type: GripperCommand
    joints:
      - openarm_right_finger_joint1
    action_ns: gripper_cmd
    default: true
=======
  
  left_gripper_controller:
    action_ns: gripper_action
    type: GripperCommand
    joints:
      - openarm_left_gripper_joint
  
  right_gripper_controller:
    action_ns: gripper_action
    type: GripperCommand
    joints:
      - openarm_right_gripper_joint
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
  left_gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - openarm_left_finger_joint1
  right_gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - openarm_right_finger_joint1
>>>>>>> 2569ad2 (feat: control)
